steps:
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args: ['-c', 'pip install -r requirements.txt && pip install pytest && pytest -q']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/labs/ship-it:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/labs/ship-it:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'ship-it',
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/labs/ship-it:$SHORT_SHA',
           '--region', 'us-central1',
           '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY
